name: RankPoints
main: JD\RankPoints\Main
version: 1.4.2
api: [2.0.0, 3.0.0-ALPHA1]
author: JD
load: POSTWORLD
commands:
  rankpoints:
    description: "Shows Rank Points"
    usage: "/rankpoints"
    
    